import { useEffect, useState } from 'react';
import { getQzCertificateStatus, saveQzCertificateFiles, type QzCertificateStatus } from '../../services/printService';

export default function QzCertificateSetup({ onSaved }: { onSaved: () => void }) {
  const [status, setStatus] = useState<QzCertificateStatus | null>(null);
  const [certificate, setCertificate] = useState<File | null>(null);
  const [privateKey, setPrivateKey] = useState<File | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [failed, setFailed] = useState(false);
  useEffect(() => {
    let live = true;
    getQzCertificateStatus().then((value) => { if (live) setStatus(value); })
      .catch((error: unknown) => { if (live) { setFailed(true); setMessage(error instanceof Error ? error.message : 'Could not read QZ certificate settings.'); } });
    return () => { live = false; };
  }, []);
  const save = async () => {
    if (!certificate || !privateKey || busy) return;
    setBusy(true); setFailed(false); setMessage('');
    try {
      setStatus(await saveQzCertificateFiles(certificate, privateKey));
      setCertificate(null); setPrivateKey(null);
      setMessage('Certificate saved. Allow and remember this trusted certificate in QZ if prompted, then refresh printers.');
      onSaved();
    } catch (error) { setFailed(true); setMessage(error instanceof Error ? error.message : 'Could not save QZ certificate.'); }
    finally { setBusy(false); }
  };
  return <div style={{ border: '1px solid var(--ch-border)', borderRadius: 12, padding: 16, marginBottom: 16 }}>
    <h4 style={{ margin: '0 0 8px' }}>QZ certificate setup</h4>
    <p className="ch-hint">Upload both files generated by QZ Site Manager to identify this POS and sign printing requests. The private key is encrypted on the server.</p>
    <p className="ch-hint">{status ? (status.configured ? `Signing configured${status.expires ? ` · expires ${status.expires}` : ''}.` : 'No signing certificate configured — QZ will show an unknown-site permission prompt.') : 'Checking signing configuration…'}</p>
    {status?.signingError && <p className="ch-hint" role="alert">{status.signingError}</p>}
    {status && !status.uploadReady && <p role="status" className="ch-hint">Certificate uploads require QZ_KEY_ENCRYPTION_SECRET on the backend. Contact your POS administrator to configure it.</p>}
    <fieldset disabled={busy} style={{ border: 0, margin: 0, padding: 0 }}>
      <div className="ch-form-grid">
        {([{ kind: 'certificate', title: 'digital-certificate.txt', file: certificate, setFile: setCertificate }, { kind: 'key', title: 'private-key.pem', file: privateKey, setFile: setPrivateKey }] as const).map((field) => <div key={field.kind} className="ch-field" onDragOver={(event) => event.preventDefault()} onDrop={(event) => {
          event.preventDefault(); if (!busy && event.dataTransfer.files[0]) field.setFile(event.dataTransfer.files[0]);
        }} style={{ border: '1px dashed var(--ch-border)', borderRadius: 8, padding: 12 }}>
          <label className="ch-label" htmlFor={`qz-${field.kind}`}>{field.title}</label>
          <input id={`qz-${field.kind}`} type="file" accept={field.kind === 'key' ? '.pem' : '.txt,.pem,.crt'} onChange={(event) => { field.setFile(event.currentTarget.files?.[0] ?? null); event.currentTarget.value = ''; }} />
          <p className="ch-hint">{field.file ? field.file.name : status?.configured ? `Saved: ${field.title}${field.kind === 'key' ? ' (encrypted on server)' : ''}. Choose a file to replace it.` : 'Choose a file or drag it here.'}</p>
        </div>)}
      </div>
      <button type="button" className="ch-btn ch-btn-secondary ch-btn-sm" disabled={!certificate || !privateKey || !status?.uploadReady} onClick={() => { void save(); }}>{busy ? 'Saving…' : 'Save certificate files'}</button>
    </fieldset>
    {message && <p className="ch-hint" role={failed ? 'alert' : 'status'}>{message}</p>}
    <p className="ch-hint">A QZ demo certificate works only on the computer where it was generated. Other client terminals must trust the certificate separately.</p>
  </div>;
}
